// Generated by gencpp from file dyret_hardware/ActuatorBoardState.msg
// DO NOT EDIT!


#ifndef DYRET_HARDWARE_MESSAGE_ACTUATORBOARDSTATE_H
#define DYRET_HARDWARE_MESSAGE_ACTUATORBOARDSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dyret_hardware
{
template <class ContainerAllocator>
struct ActuatorBoardState_
{
  typedef ActuatorBoardState_<ContainerAllocator> Type;

  ActuatorBoardState_()
    : position()  {
      position.assign(0.0);
  }
  ActuatorBoardState_(const ContainerAllocator& _alloc)
    : position()  {
  (void)_alloc;
      position.assign(0.0);
  }



   typedef boost::array<float, 8>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorBoardState_

typedef ::dyret_hardware::ActuatorBoardState_<std::allocator<void> > ActuatorBoardState;

typedef boost::shared_ptr< ::dyret_hardware::ActuatorBoardState > ActuatorBoardStatePtr;
typedef boost::shared_ptr< ::dyret_hardware::ActuatorBoardState const> ActuatorBoardStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dyret_hardware::ActuatorBoardState_<ContainerAllocator1> & lhs, const ::dyret_hardware::ActuatorBoardState_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dyret_hardware::ActuatorBoardState_<ContainerAllocator1> & lhs, const ::dyret_hardware::ActuatorBoardState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dyret_hardware

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61a2e72fc291b8e237e79adac79aac78";
  }

  static const char* value(const ::dyret_hardware::ActuatorBoardState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61a2e72fc291b8e2ULL;
  static const uint64_t static_value2 = 0x37e79adac79aac78ULL;
};

template<class ContainerAllocator>
struct DataType< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dyret_hardware/ActuatorBoardState";
  }

  static const char* value(const ::dyret_hardware::ActuatorBoardState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[8] position\n"
;
  }

  static const char* value(const ::dyret_hardware::ActuatorBoardState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorBoardState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dyret_hardware::ActuatorBoardState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dyret_hardware::ActuatorBoardState_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYRET_HARDWARE_MESSAGE_ACTUATORBOARDSTATE_H
