# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msgs/valve_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class valve_msg(genpy.Message):
  _md5sum = "2365f6928f3a6bbdd43c68c9166e3c42"
  _type = "custom_msgs/valve_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 PWM_duty
uint8 PWM_freq
uint8 PWM_valve_nr
"""
  __slots__ = ['PWM_duty','PWM_freq','PWM_valve_nr']
  _slot_types = ['uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       PWM_duty,PWM_freq,PWM_valve_nr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(valve_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.PWM_duty is None:
        self.PWM_duty = 0
      if self.PWM_freq is None:
        self.PWM_freq = 0
      if self.PWM_valve_nr is None:
        self.PWM_valve_nr = 0
    else:
      self.PWM_duty = 0
      self.PWM_freq = 0
      self.PWM_valve_nr = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.PWM_duty, _x.PWM_freq, _x.PWM_valve_nr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.PWM_duty, _x.PWM_freq, _x.PWM_valve_nr,) = _get_struct_3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.PWM_duty, _x.PWM_freq, _x.PWM_valve_nr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.PWM_duty, _x.PWM_freq, _x.PWM_valve_nr,) = _get_struct_3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
