// Generated by gencpp from file dyret_common/Configuration.msg
// DO NOT EDIT!


#ifndef DYRET_COMMON_MESSAGE_CONFIGURATION_H
#define DYRET_COMMON_MESSAGE_CONFIGURATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dyret_common/RevoluteConfig.h>
#include <dyret_common/PrismaticConfig.h>

namespace dyret_common
{
template <class ContainerAllocator>
struct Configuration_
{
  typedef Configuration_<ContainerAllocator> Type;

  Configuration_()
    : header()
    , revolute()
    , prismatic()  {
    }
  Configuration_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , revolute(_alloc)
    , prismatic(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::dyret_common::RevoluteConfig_<ContainerAllocator>  _revolute_type;
  _revolute_type revolute;

   typedef  ::dyret_common::PrismaticConfig_<ContainerAllocator>  _prismatic_type;
  _prismatic_type prismatic;





  typedef boost::shared_ptr< ::dyret_common::Configuration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dyret_common::Configuration_<ContainerAllocator> const> ConstPtr;

}; // struct Configuration_

typedef ::dyret_common::Configuration_<std::allocator<void> > Configuration;

typedef boost::shared_ptr< ::dyret_common::Configuration > ConfigurationPtr;
typedef boost::shared_ptr< ::dyret_common::Configuration const> ConfigurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dyret_common::Configuration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dyret_common::Configuration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dyret_common::Configuration_<ContainerAllocator1> & lhs, const ::dyret_common::Configuration_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.revolute == rhs.revolute &&
    lhs.prismatic == rhs.prismatic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dyret_common::Configuration_<ContainerAllocator1> & lhs, const ::dyret_common::Configuration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dyret_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dyret_common::Configuration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dyret_common::Configuration_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dyret_common::Configuration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dyret_common::Configuration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dyret_common::Configuration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dyret_common::Configuration_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dyret_common::Configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "118b2ad5ce546e709acfc0ea7ee160e9";
  }

  static const char* value(const ::dyret_common::Configuration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x118b2ad5ce546e70ULL;
  static const uint64_t static_value2 = 0x9acfc0ea7ee160e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::dyret_common::Configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dyret_common/Configuration";
  }

  static const char* value(const ::dyret_common::Configuration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dyret_common::Configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message represents the configuration of the servos\n"
"#\n"
"# - The configuration is applied to all servos if the id array is empty.\n"
"# - All parameters are added sequentially in the parameter field, so\n"
"# the length of this array may be a multiple of the number of servos in\n"
"# cases where there are more than one parameter per servo needed\n"
"\n"
"# Header for general bookkeeping\n"
"std_msgs/Header header\n"
"\n"
"dyret_common/RevoluteConfig revolute\n"
"dyret_common/PrismaticConfig prismatic\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dyret_common/RevoluteConfig\n"
"# This message represents the configuration of the revolute joints\n"
"#\n"
"# - The configuration is applied to all joints if the id array is empty.\n"
"# - All parameters are added sequentially in the parameter field, so\n"
"# the length of this array may be a multiple of the number of joints in\n"
"# cases where there are more than one parameter per joint needed\n"
"\n"
"# Joint IDs\n"
"uint8[] ids\n"
"\n"
"# Configuration parameters\n"
"float64[] parameters\n"
"\n"
"# Configuration type\n"
"uint8 type\n"
"\n"
"uint8 TYPE_SET_SPEED      = 0\n"
"uint8 TYPE_SET_PID        = 1\n"
"uint8 TYPE_ENABLE_TORQUE  = 2\n"
"uint8 TYPE_DISABLE_TORQUE = 3\n"
"\n"
"================================================================================\n"
"MSG: dyret_common/PrismaticConfig\n"
"# This message represents the configuration of the prismatic joints\n"
"#\n"
"# - The configuration is applied to all joints if the id array is empty.\n"
"# - All parameters are added sequentially in the parameter field, so\n"
"# the length of this array may be a multiple of the number of joints in\n"
"# cases where there are more than one parameter per joint needed\n"
"\n"
"# Joint IDs\n"
"uint8[] ids\n"
"\n"
"# Configuration parameters\n"
"float64[] parameters\n"
"\n"
"# Configuration type\n"
"uint8 type\n"
"\n"
"uint8 TYPE_SET_PID = 1\n"
;
  }

  static const char* value(const ::dyret_common::Configuration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dyret_common::Configuration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.revolute);
      stream.next(m.prismatic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Configuration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dyret_common::Configuration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dyret_common::Configuration_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "revolute: ";
    s << std::endl;
    Printer< ::dyret_common::RevoluteConfig_<ContainerAllocator> >::stream(s, indent + "  ", v.revolute);
    s << indent << "prismatic: ";
    s << std::endl;
    Printer< ::dyret_common::PrismaticConfig_<ContainerAllocator> >::stream(s, indent + "  ", v.prismatic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYRET_COMMON_MESSAGE_CONFIGURATION_H
