// Generated by gencpp from file dyret_common/Configure.msg
// DO NOT EDIT!


#ifndef DYRET_COMMON_MESSAGE_CONFIGURE_H
#define DYRET_COMMON_MESSAGE_CONFIGURE_H

#include <ros/service_traits.h>


#include <dyret_common/ConfigureRequest.h>
#include <dyret_common/ConfigureResponse.h>


namespace dyret_common
{

struct Configure
{

typedef ConfigureRequest Request;
typedef ConfigureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Configure
} // namespace dyret_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dyret_common::Configure > {
  static const char* value()
  {
    return "a1f60ce87d284338086c76bca2c0d0f8";
  }

  static const char* value(const ::dyret_common::Configure&) { return value(); }
};

template<>
struct DataType< ::dyret_common::Configure > {
  static const char* value()
  {
    return "dyret_common/Configure";
  }

  static const char* value(const ::dyret_common::Configure&) { return value(); }
};


// service_traits::MD5Sum< ::dyret_common::ConfigureRequest> should match
// service_traits::MD5Sum< ::dyret_common::Configure >
template<>
struct MD5Sum< ::dyret_common::ConfigureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dyret_common::Configure >::value();
  }
  static const char* value(const ::dyret_common::ConfigureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dyret_common::ConfigureRequest> should match
// service_traits::DataType< ::dyret_common::Configure >
template<>
struct DataType< ::dyret_common::ConfigureRequest>
{
  static const char* value()
  {
    return DataType< ::dyret_common::Configure >::value();
  }
  static const char* value(const ::dyret_common::ConfigureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dyret_common::ConfigureResponse> should match
// service_traits::MD5Sum< ::dyret_common::Configure >
template<>
struct MD5Sum< ::dyret_common::ConfigureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dyret_common::Configure >::value();
  }
  static const char* value(const ::dyret_common::ConfigureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dyret_common::ConfigureResponse> should match
// service_traits::DataType< ::dyret_common::Configure >
template<>
struct DataType< ::dyret_common::ConfigureResponse>
{
  static const char* value()
  {
    return DataType< ::dyret_common::Configure >::value();
  }
  static const char* value(const ::dyret_common::ConfigureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYRET_COMMON_MESSAGE_CONFIGURE_H
