// Generated by gencpp from file dyret_common/State.msg
// DO NOT EDIT!


#ifndef DYRET_COMMON_MESSAGE_STATE_H
#define DYRET_COMMON_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dyret_common/RevoluteState.h>
#include <dyret_common/PrismaticState.h>

namespace dyret_common
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : header()
    , revolute()
    , prismatic()  {
    }
  State_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , revolute()
    , prismatic()  {
  (void)_alloc;
      revolute.assign( ::dyret_common::RevoluteState_<ContainerAllocator> (_alloc));

      prismatic.assign( ::dyret_common::PrismaticState_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array< ::dyret_common::RevoluteState_<ContainerAllocator> , 12>  _revolute_type;
  _revolute_type revolute;

   typedef boost::array< ::dyret_common::PrismaticState_<ContainerAllocator> , 8>  _prismatic_type;
  _prismatic_type prismatic;





  typedef boost::shared_ptr< ::dyret_common::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dyret_common::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::dyret_common::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::dyret_common::State > StatePtr;
typedef boost::shared_ptr< ::dyret_common::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dyret_common::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dyret_common::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dyret_common::State_<ContainerAllocator1> & lhs, const ::dyret_common::State_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.revolute == rhs.revolute &&
    lhs.prismatic == rhs.prismatic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dyret_common::State_<ContainerAllocator1> & lhs, const ::dyret_common::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dyret_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dyret_common::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dyret_common::State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dyret_common::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dyret_common::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dyret_common::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dyret_common::State_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dyret_common::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "199e494597c0c7034abea6bdf1e7efee";
  }

  static const char* value(const ::dyret_common::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x199e494597c0c703ULL;
  static const uint64_t static_value2 = 0x4abea6bdf1e7efeeULL;
};

template<class ContainerAllocator>
struct DataType< ::dyret_common::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dyret_common/State";
  }

  static const char* value(const ::dyret_common::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dyret_common::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message is intended as the output of Dyret\n"
"\n"
"# Header for general bookkeeping\n"
"std_msgs/Header header\n"
"\n"
"# State of revolute joints\n"
"dyret_common/RevoluteState[12] revolute\n"
"# State of prismatic joints\n"
"dyret_common/PrismaticState[8] prismatic\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dyret_common/RevoluteState\n"
"# This message represents the state of a single revolute joint\n"
"# it is not meant to be used alone, but as a part of other\n"
"# messages, see 'State'.\n"
"\n"
"# Joint state\n"
"float32 position\n"
"float32 velocity\n"
"float32 current\n"
"\n"
"# Physical state\n"
"float32 voltage\n"
"float32 temperature\n"
"\n"
"# Controller state\n"
"float32 set_point\n"
"float32 error\n"
"\n"
"# Joint status:\n"
"uint8 status\n"
"\n"
"uint8 STATUS_NOERROR       = 0\n"
"uint8 STATUS_INSTRUCTION   = 1\n"
"uint8 STATUS_OVERLOAD      = 2\n"
"uint8 STATUS_CHECKSUM      = 3\n"
"uint8 STATUS_RANGE         = 4\n"
"uint8 STATUS_OVERHEATING   = 5\n"
"uint8 STATUS_ANGLE_LIMIT   = 6\n"
"uint8 STATUS_INPUT_VOLTAGE = 7\n"
"\n"
"================================================================================\n"
"MSG: dyret_common/PrismaticState\n"
"# This message represents the state of a single prismatic joint\n"
"# it is not meant to be used alone, but as a part of other\n"
"# messages, see 'State'.\n"
"\n"
"# Joint state\n"
"float32 position\n"
"\n"
"# Controller state\n"
"float32 set_point\n"
"float32 error\n"
;
  }

  static const char* value(const ::dyret_common::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dyret_common::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.revolute);
      stream.next(m.prismatic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dyret_common::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dyret_common::State_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "revolute[]" << std::endl;
    for (size_t i = 0; i < v.revolute.size(); ++i)
    {
      s << indent << "  revolute[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dyret_common::RevoluteState_<ContainerAllocator> >::stream(s, indent + "    ", v.revolute[i]);
    }
    s << indent << "prismatic[]" << std::endl;
    for (size_t i = 0; i < v.prismatic.size(); ++i)
    {
      s << indent << "  prismatic[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dyret_common::PrismaticState_<ContainerAllocator> >::stream(s, indent + "    ", v.prismatic[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYRET_COMMON_MESSAGE_STATE_H
