// Generated by gencpp from file custom_msgs/encoder_msg.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_ENCODER_MSG_H
#define CUSTOM_MSGS_MESSAGE_ENCODER_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct encoder_msg_
{
  typedef encoder_msg_<ContainerAllocator> Type;

  encoder_msg_()
    : pos(0)  {
    }
  encoder_msg_(const ContainerAllocator& _alloc)
    : pos(0)  {
  (void)_alloc;
    }



   typedef int16_t _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::custom_msgs::encoder_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::encoder_msg_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_msg_

typedef ::custom_msgs::encoder_msg_<std::allocator<void> > encoder_msg;

typedef boost::shared_ptr< ::custom_msgs::encoder_msg > encoder_msgPtr;
typedef boost::shared_ptr< ::custom_msgs::encoder_msg const> encoder_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::encoder_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::encoder_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rosserial_msgs': ['/home/saitama/catkin_ws/src/rosserial/rosserial_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/saitama/catkin_ws/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::encoder_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::encoder_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::encoder_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::encoder_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::encoder_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::encoder_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::encoder_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff6a9630c81cddcd0e429fac19f3bfaa";
  }

  static const char* value(const ::custom_msgs::encoder_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff6a9630c81cddcdULL;
  static const uint64_t static_value2 = 0x0e429fac19f3bfaaULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::encoder_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/encoder_msg";
  }

  static const char* value(const ::custom_msgs::encoder_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::encoder_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 pos\n"
;
  }

  static const char* value(const ::custom_msgs::encoder_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::encoder_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::encoder_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::encoder_msg_<ContainerAllocator>& v)
  {
    s << indent << "pos: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_ENCODER_MSG_H
