// Generated by gencpp from file custom_msgs/servo_msg.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_SERVO_MSG_H
#define CUSTOM_MSGS_MESSAGE_SERVO_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct servo_msg_
{
  typedef servo_msg_<ContainerAllocator> Type;

  servo_msg_()
    : id(0)
    , pos(0)
    , speed(0)  {
    }
  servo_msg_(const ContainerAllocator& _alloc)
    : id(0)
    , pos(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef int8_t _id_type;
  _id_type id;

   typedef int16_t _pos_type;
  _pos_type pos;

   typedef int16_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::custom_msgs::servo_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::servo_msg_<ContainerAllocator> const> ConstPtr;

}; // struct servo_msg_

typedef ::custom_msgs::servo_msg_<std::allocator<void> > servo_msg;

typedef boost::shared_ptr< ::custom_msgs::servo_msg > servo_msgPtr;
typedef boost::shared_ptr< ::custom_msgs::servo_msg const> servo_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::servo_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::servo_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::servo_msg_<ContainerAllocator1> & lhs, const ::custom_msgs::servo_msg_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pos == rhs.pos &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::servo_msg_<ContainerAllocator1> & lhs, const ::custom_msgs::servo_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::servo_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::servo_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::servo_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::servo_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::servo_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::servo_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::servo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4746890200c2a955023cca7b744b47b3";
  }

  static const char* value(const ::custom_msgs::servo_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4746890200c2a955ULL;
  static const uint64_t static_value2 = 0x023cca7b744b47b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::servo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/servo_msg";
  }

  static const char* value(const ::custom_msgs::servo_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::servo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 id\n"
"int16 pos\n"
"int16 speed\n"
;
  }

  static const char* value(const ::custom_msgs::servo_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::servo_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pos);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servo_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::servo_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::servo_msg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "pos: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pos);
    s << indent << "speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_SERVO_MSG_H
