// Generated by gencpp from file custom_msgs/valve_msg.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_VALVE_MSG_H
#define CUSTOM_MSGS_MESSAGE_VALVE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct valve_msg_
{
  typedef valve_msg_<ContainerAllocator> Type;

  valve_msg_()
    : PWM_duty(0)
    , PWM_freq(0)
    , PWM_valve_nr(0)  {
    }
  valve_msg_(const ContainerAllocator& _alloc)
    : PWM_duty(0)
    , PWM_freq(0)
    , PWM_valve_nr(0)  {
  (void)_alloc;
    }



   typedef uint8_t _PWM_duty_type;
  _PWM_duty_type PWM_duty;

   typedef uint8_t _PWM_freq_type;
  _PWM_freq_type PWM_freq;

   typedef uint8_t _PWM_valve_nr_type;
  _PWM_valve_nr_type PWM_valve_nr;





  typedef boost::shared_ptr< ::custom_msgs::valve_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::valve_msg_<ContainerAllocator> const> ConstPtr;

}; // struct valve_msg_

typedef ::custom_msgs::valve_msg_<std::allocator<void> > valve_msg;

typedef boost::shared_ptr< ::custom_msgs::valve_msg > valve_msgPtr;
typedef boost::shared_ptr< ::custom_msgs::valve_msg const> valve_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::valve_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::valve_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::valve_msg_<ContainerAllocator1> & lhs, const ::custom_msgs::valve_msg_<ContainerAllocator2> & rhs)
{
  return lhs.PWM_duty == rhs.PWM_duty &&
    lhs.PWM_freq == rhs.PWM_freq &&
    lhs.PWM_valve_nr == rhs.PWM_valve_nr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::valve_msg_<ContainerAllocator1> & lhs, const ::custom_msgs::valve_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::valve_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::valve_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::valve_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::valve_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::valve_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::valve_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::valve_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2365f6928f3a6bbdd43c68c9166e3c42";
  }

  static const char* value(const ::custom_msgs::valve_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2365f6928f3a6bbdULL;
  static const uint64_t static_value2 = 0xd43c68c9166e3c42ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::valve_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/valve_msg";
  }

  static const char* value(const ::custom_msgs::valve_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::valve_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 PWM_duty\n"
"uint8 PWM_freq\n"
"uint8 PWM_valve_nr\n"
;
  }

  static const char* value(const ::custom_msgs::valve_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::valve_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.PWM_duty);
      stream.next(m.PWM_freq);
      stream.next(m.PWM_valve_nr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct valve_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::valve_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::valve_msg_<ContainerAllocator>& v)
  {
    s << indent << "PWM_duty: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.PWM_duty);
    s << indent << "PWM_freq: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.PWM_freq);
    s << indent << "PWM_valve_nr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.PWM_valve_nr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_VALVE_MSG_H
